name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm build

    - name: Run tests
      run: npm test

    - name: Run lint
      run: npm lint
