name: CI/CD Workflow

on: [push]

jobs:
  entire_workflow:
    name: CI/CD Process
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run build
      run: npm run build

    - name: Run lint
      run: npm run lint

    - name: Execute tests
      run: npm run test

    - name: Release (only on main branch)
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        npm run release
