name: CI/CD Workflow

on: [push]

jobs:
  setup:
    name: Setup & Install Dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run build
      run: npm run build

  lint:
      name: Lint Code
      runs-on: ubuntu-latest
      needs: setup

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run lint
        run: npm run lint
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [setup, build, lint]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute tests
      run: npm run test

  release:
    name: Release Process
    runs-on: ubuntu-latest
    needs: [tests]
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git for release
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run release